name: itm8_attendance

services:
  itm8_attendance_backend:
    build: 
      context: ./backend
    container_name: itm8_attendance_backend
    restart: always
    ports:
      - "8050:8000"
    env_file:
      - ./backend/.env
    networks:
      - itm8_attendance
      - itm8_db
    volumes:
      - uploads:/app/uploads

  itm8_attendance_redis:
    image: redis:alpine
    container_name: itm8_attendance_redis
    restart: always
    networks:
      - itm8_attendance
    volumes:
      - redis_data:/data

  itm8_attendance_frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://10.113.234.25:8050
    env_file:
      - ./frontend/.env
    container_name: itm8_attendance_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - itm8_attendance_backend
    networks:
      - itm8_attendance
    volumes:
      - uploads:/usr/share/nginx/html/uploads

networks:
  itm8_attendance:
    name: itm8_attendance
    driver: bridge
  itm8_db:
    name: itm8_db
    external: true

volumes:
  uploads:
    name: itm8_attendance_uploads
  redis_data:
    name: itm8_attendance_redis_data
