name: itm8-attendance

services:
  itm8_attendance_backend:
    build: 
      context: ./backend
    container_name: itm8_attendance_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - itm8-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  itm8_attendance_redis:
    image: redis:alpine
    container_name: itm8_attendance_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - itm8-network

  itm8_attendance_frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    env_file:
      - ./frontend/.env
    container_name: itm8_attendance_frontend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - itm8_attendance_backend
    networks:
      - itm8-network

networks:
  itm8-network:
    driver: bridge
